name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '40 7 * * 3'
  workflow_dispatch:

permissions:
  # Allows SonarCloud to decorate PRs with analysis results
  pull-requests: write

env:
  # Set the build directory for the build-wrapper output
  BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory "$
  BUILD_OUTPUT_DIR: build/

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        preset: [px-release]
        platform: [ubuntu-latest]

    # e.g., "Build | px-release âš™ï¸"
    name: "Build | ${{ matrix.preset }} âš™ï¸"
    runs-on: "${{matrix.platform}}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '~3.25.0'
          ninjaVersion: '^1.11.1'

      - if: matrix.platform == 'windows-latest'
        name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: >-
          cmake -S . -B "${{ env.BUILD_OUTPUT_DIR }}" --preset="${{ matrix.preset }}"

      - name: Build
        run: >-
          cmake --build "${{ env.BUILD_OUTPUT_DIR }}"

  analyze:
    needs: build
    timeout-minutes: 360
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: write

      # only required for workflows in private repositories
      actions: write
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: c-cpp
            build-mode: manual
            tool: codeql
            os: windows-latest
            platform: windows
            preset: vc17win64
            preset: px-release
          - language: c-cpp
            build-mode: manual
            tool: sonar
            os: ubuntu-latest
            platform: linux
            preset: linux-aarch64
            preset: px-release
          - language: python
            build-mode: none
            tool: codeql
            os: ubuntu-latest
            platform: linux
            preset: python
            preset: px-release

    name: "Analyze ${{ matrix.language }} ðŸ”"
    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - if: ${{ matrix.tool == 'sonar' }}
        name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v2

      # Initializes the CodeQL tools for scanning.
      - if: ${{ matrix.tool == 'codeql' }}
        name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '~3.25.0'
          ninjaVersion: '^1.11.1'

      - if: matrix.build-mode == 'manual'
        name: Configure CMake
        run: >-
          cmake -S . -B "${{ env.BUILD_OUTPUT_DIR }}" -DCMAKE_BUILD_TYPE="${{ matrix.preset }}"

      - if: ${{ matrix.tool == 'sonar' && matrix.build-mode == 'manual' }}
        name: Build
        run: cmake --build "${{ env.BUILD_OUTPUT_DIR }}"

      - if: ${{ matrix.tool == 'sonar' }}
        name: Run build-wrapper
        run: >-
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }}
          cmake --build "${{ env.BUILD_OUTPUT_DIR }}"

      - if: ${{ matrix.tool == 'sonar' }}
        name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          sonar-scanner --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"

      - if: ${{ matrix.tool == 'codeql' }}
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{matrix.language}}'
